version:"3"
networks:
  app-network:
    driver:bridge
  services:
    timesheet:
      container_name:"timesheet"
      build: .
      expose:
        -"8088"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://192.168.249.1:3306/devopsdb
      networks:
        - app-network  
      restart: unless-stopped
