version:"3"
networks:
  app-network:
    driver:bridge
  services:
    timesheet:
      container_name:"timesheet"
      build: .
      expose:
        -"8088"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hemisphere
      networks:
        - app-network  
      restart: unless-stopped